### ISSUE TITLE
Pressing TAB or arrow key throws TypeError with simple example from GitHub

### ISSUE THREAD

**Issue by ZipBrandon** [tomsouthall/turnstone#3] opened 2022-03-25 15:53 UTC
This may be related to #2 but when I press TAB or arrow key it throws an TypeError. 

https://codesandbox.io/s/hidden-breeze-lre13y

![image](https://user-images.githubusercontent.com/68867795/160155415-f9f4760f-28a3-45a6-a755-9deca6f59947.png)

**Comment by tomsouthall** [comment] 2022-03-25 16:26
I have found the cause and will be releasing a fix shortly

**Comment by tomsouthall** [comment] 2022-03-25 16:39
Fixed in v1.2.2. Thanks for flagging this.

**Closed by tomsouthall** 2022-03-25 16:39 UTC

**Comment by tomsouthall** [comment] 2022-03-25 16:51
Here is your example updated with the latest version which fixes the issue

https://codesandbox.io/s/tender-hopper-kql1rr
